FROM python:3.8

# Set the working directory
WORKDIR /url_shortener

# Copy the application files to the working directory in the container
COPY . .

# Install application dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Run the application
CMD ["python", "main.py"]
